<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
    <AssemblyName>FlashCards</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="TestScraper\**" />
    <Compile Remove="FlashCardsCore\**" />
    <Content Remove="TestScraper\**" />
    <Content Remove="FlashCardsCore\**" />
    <None Remove="TestScraper\**" />
    <None Remove="FlashCardsCore\**" />
    <Content Include="Webviews\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Speech" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
